name: Documenter
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - name: Cache
        uses: julia-actions/cache@v1
        with:
            cache-compiled: "true"
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # when run by tagbot
